### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Khitiara** [02JanDal/QuickModDoc#6]
- Source and Deobfuscated urls (optional elements)
- Arbitrary metadata object:

``` json
{
    "versions": [
        {
        ...
            "metadata": {
            }
        ...
        }
        ...
    ]
}
```

**Comment by 02JanDal** [comment]
Different URLs: IMO that should be handled by something like maven files. We can keep this in consideration though, but it'll have to wait until the rest of the format is somewhat stable.

Metadata: What for? I don't really get it's use.

**Comment by Khitiara** [comment]
I generate my dl page from qmods, and there may be other info you want the user to see
as for deobf/src urls maybe have a new url type that gets ignored by the downloader?
